pypy3 problem.py < tests/01.txt
pypy3 problem.py < tests/02.txt
pypy3 problem.py < tests/03.txt
pypy3 problem.py < tests/04.txt
pypy3 problem.py < tests/05.txt
pypy3 problem.py < tests/06.txt
pypy3 problem.py < tests/07.txt
pypy3 problem.py < tests/08.txt
pypy3 problem.py < tests/09.txt
pypy3 problem.py < tests/10.txt
pypy3 problem.py < tests/11.txt
pypy3 problem.py < tests/12.txt
pypy3 problem.py < tests/13.txt
pypy3 problem.py < tests/14.txt
pypy3 problem.py < tests/15.txt
pypy3 problem.py < tests/16.txt
pypy3 problem.py < tests/17.txt
pypy3 problem.py < tests/18.txt
pypy3 problem.py < tests/19.txt
pypy3 problem.py < tests/20.txt